### ISSUE TITLE
Curves of the templates.

### ISSUE THREAD

**Issue by satyam-sahoo-1** [subhashissuara/subhashissuara.github.io#1]
The curves of the templates can be managed in a better way.
![Capture](https://user-images.githubusercontent.com/78195612/115961242-379ec800-a533-11eb-8e48-ba9b1315d7e0.JPG)

**Comment by subhashissuara** [comment]
Sure! Make a PR with screenshot of issue being fixed and tag this issue in the PR.

**Comment by satyam-sahoo-1** [comment]
It has been fixed.
